name: Daily Manga Video

on:
  schedule:
    # Runs every day at 18:30 Europe/Ljubljana ≈ 17:30 UTC (adjust for DST)
    - cron: "30 17 * * *"
  workflow_dispatch: {}

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          mkdir -p output
          python main.py

      - name: Upload video artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tiktok-video
          path: output/tiktok_video.mp4
